[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "github.com/docker/docker"

[[constraint]]
  name = "github.com/riemann/riemann-go-client"
  version = "0.4.0"
